name: pytest

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.2
      - name: Set Poetry config
        run: |
          poetry config settings.virtualenvs.in-project false
      - name: Install Dependencies
        run: poetry install
      - name: Running pytest
        run: poerty run test
