name: Release
on:
  release:
    types:
      - created
  workflows_run:
    workflows: [Push]
    types:
      - completed

jobs:
  docs:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
      - uses: actions/upload-artifact@v1
        with:
          name: DocumentationHTML
          path: docs/_build/html/
  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        poetry-version: [1.3.1]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build